name: Deploy to Fly.io

on:
  push:
    tags:
      - 'v*'
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug info
        run: |
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_type = ${{ github.ref_type }}"
          echo "github.event_name = ${{ github.event_name }}"
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 23
          
      - name: Install dependencies
        run: npm ci
        
      # - name: Run tests
      #   run: npm test
        
      - name: Build
        run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v3

      # Get the version from the tag
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Setup Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --env APP_VERSION=${{ steps.get_version.outputs.VERSION }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}