name: Rollback Deployment
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag/version to rollback to (e.g., v1.2.3)"
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version }} # Checkout specific tag

      - name: Setup Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy specific version
        run: flyctl deploy --remote-only --env APP_VERSION=${{ github.event.inputs.version }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
